@host = localhost:3000

###
GET /files
Host: {{host}}
Content-Type: application/json

###
POST /files/delete
Host: {{host}}
Content-Type: application/json

{
    "files":[
        "/home/location/to/directory/fileMgmt/uploads/biometric/fingerprint/banner2_1709229138762.jpg"]
}

